// Voice rules and voice-direction context for Ch4 « Mesurer deux fois » (src/story/ch4.js, ch4crafts.js, crafts/*).
// Read by scripts/voice/extract-lines.mjs (rule syntax and kinds: see the table comment there). The chapter's
// builder owns this file: add a rule for every new text key, or extract-lines reports it as UNCLASSIFIED.

export const RULES = [
  ['ch4.title', { kind: 'none', why: 'title' }],
  ['ch4.cards.**', { kind: 'none', why: 'card' }],
  ['ch4.objectives.**', { kind: 'none', why: 'objective' }],
  ['ch4.prompts.**', { kind: 'none', why: 'prompt' }],
  ['ch4.signs.**', { kind: 'none', why: 'sign' }],
  ['ch4.oldSigns', { kind: 'say', use: 'd.say(T4.oldSigns)' }],
  ['ch4.radio', { kind: 'say', use: 'd.say(T4.radio)' }],
  ['ch4.day5.*', { kind: 'say', use: 'd.say(T4.day5.<beat>)' }],
  ['ch4.sanding.gauge', { kind: 'none', why: 'ui' }],
  ['ch4.sanding.hint', { kind: 'none', why: 'hint' }],
  ['ch4.sanding.barks', { kind: 'bark', use: 'ch4crafts: ui.thought(SD.barks.mash[i] | SD.barks.cross, 2.4, {who})' }],
  ['ch4.sanding.buzz', { kind: 'none', why: 'watch' }],
  ['ch4.sanding.buzzReply', { kind: 'think', use: 'd.thought(SD.buzzReply, 2)' }],
  ['ch4.day8.start', { kind: 'say', use: 'd.say(T4.day8.start)' }],
  ['ch4.day8.tape.hint', { kind: 'none', why: 'hint' }],
  ['ch4.day8.tape.readings', { kind: 'say', use: 'tape.js: d.say([text.readings[i]]) (i = measured value)', flags: ['selected-at-runtime'] }],
  ['ch4.day8.tape.again', { kind: 'say', use: 'tape.js: d.say([text.again[i]])', flags: ['selected-at-runtime'] }],
  ['ch4.day8.tape.twice', { kind: 'say', use: 'tape.js: d.say(text.twice)' }],
  ['ch4.day8.tape.differ', { kind: 'say', use: 'tape.js: d.say([line, ...text.help])', flags: ['selected-at-runtime'] }],
  ['ch4.day8.tape.short', { kind: 'bark', use: 'tape.js: ui.thought(text.short.text, 2.4, {who})' }],
  ['ch4.day8.tape.help', { kind: 'say', use: 'tape.js: d.say([line, ...text.help])' }],
  ['ch4.day8.tape.cut', { kind: 'say', use: 'ch4.js: d.say([T4.day8.tape.cut[readingIndex(m.agreed)]])', flags: ['selected-at-runtime'] }],
  ['ch4.day8.grey', { kind: 'say', use: 'd.say(T4.day8.grey)' }],
  ['ch4.day8.mixer.intro', { kind: 'say', use: 'mixer.js: d.say(text.intro)' }],
  ['ch4.day8.mixer.tins.**', { kind: 'none', why: 'ui' }],
  ['ch4.day8.mixer.hint', { kind: 'none', why: 'hint' }],
  ['ch4.day8.mixer.tip', { kind: 'none', why: 'ui' }],
  ['ch4.day8.mixer.done', { kind: 'none', why: 'ui' }],
  ['ch4.day8.mixer.full', { kind: 'bark', use: 'mixer.js: ui.thought(text.full.text, 2.4, {who})' }],
  ['ch4.day8.mixer.verdicts.*', { kind: 'say', use: 'mixer.js: d.say([...text.verdicts[v], text.hints[n]?])', flags: ['selected-at-runtime'] }],
  ['ch4.day8.mixer.hints', { kind: 'say', use: 'mixer.js: ui.thought(h.text, 5, {who}) AND appended to d.say(verdict lines)', flags: ['also-bark'] }],
  ['ch4.day8.mixer.warm', { kind: 'say', use: 'mixer.js: ui.thought(text.warm.text, 5, {who}) AND appended to d.say(verdict lines)', flags: ['also-bark'] }],
  ['ch4.day8.mixer.give', { kind: 'say', use: 'mixer.js: d.say(text.give)' }],
  ['ch4.day8.greyLook', { kind: 'say', use: 'mixer.js: stage line after the "light" verdict' }],
  ['ch4.day8.paintColor', { kind: 'none', why: 'data' }],
  ['ch4.day8.painted', { kind: 'say', use: 'd.say(T4.day8.painted)' }],
  // Revision 4 (docs/SCRIPT-R4.md §5)
  ['ch4.needs.*', { kind: 'say', use: 'required(..., {needs, needsLine: T4.needs.<spot>}) -> Hotspots d.say when the item is not in the pocket' }],
  ['ch4.day8.tapeTake', { kind: 'say', use: 'd.say(T4.day8.tapeTake) at the pegboard (then item+ tape)' }],
  ['ch4.day8.hook', { kind: 'say', use: 'd.say(T4.day8.hook) at the pegboard after the grey; the chapter ends on it' }],
];

// Longest-prefix match on the key path; to / mood can be per speaker. English: direction for the voice model.
export const CONTEXT = [
  ['ch4', { scene: "Ch4: Odile's cluttered repair workshop, weeks of work", to: { odile: 'Hugo', hugo: 'Odile', sami: 'Hugo' }, mood: { odile: 'dry, practical, bossy', hugo: 'dry, slowly thawing', sami: 'cheeky' } }],
  ['ch4.oldSigns', { scene: 'Ch4: a stack of old shop signs, "MARCHAL & FILLE"', to: { hugo: 'Odile (reading the sign)', odile: 'Hugo' }, mood: { hugo: 'reading aloud', odile: 'matter-of-fact, grief buried deep' } }],
  ['ch4.radio', { scene: 'Ch4: her one-station radio', to: 'Hugo', mood: 'deadpan' }],
  ['ch4.day5', { scene: 'Ch4, day 5: Hugo\'s first morning at the workshop; the notebook "what I can do"', to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'brisk, dry, teaching by orders', hugo: 'wry, a bit lost' } }],
  ['ch4.day5.strikeThink', { scene: 'Ch4, day 5: both his skills crossed out by ten past ten', to: 'himself', mood: 'dry, self-mocking' }],
  ['ch4.day5.pegboard', { scene: 'Ch4: tool outlines painted on the pegboard', to: 'himself', mood: 'reflective' }],
  ['ch4.sanding', { scene: 'Ch4: Hugo sands the old door; Odile watches from the bench', to: { odile: 'Hugo, across the room', hugo: 'the watch' }, mood: { odile: 'dry correction', hugo: 'curt refusal' } }],
  ['ch4.day8', { scene: 'Ch4, day 8: measuring the frame and mixing a grey', to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'dry, exacting', hugo: 'concentrating' } }],
  ['ch4.day8.tape.readings', { scene: 'Ch4: reading the tape measure at the door frame', to: 'Odile', mood: 'concentrating, reading a number' }],
  ['ch4.day8.tape.again', { scene: 'Ch4: re-reading the tape after "measure twice"', to: 'Odile', mood: 'slight doubt, checking' }],
  ['ch4.day8.mixer', { scene: 'Ch4: Odile judges each grey he mixes', to: 'Hugo', mood: 'withering wit; the target line is quiet approval' }],
  ['ch4.needs', { scene: 'Ch4: Hugo at a job without the tool it needs', to: 'himself', mood: 'dry; "Deux fois." after a small beat' }],
  ['ch4.day8.tapeTake', { scene: 'Ch4, day 8: taking the tape measure off its painted outline on the pegboard', to: 'himself', mood: 'reflective, wry' }],
  ['ch4.day8.hook', { scene: 'Ch4, day 8 evening: Hugo goes to hang the tape back; Odile, from her bench, lets him keep it; an empty spoke-key outline on the board', to: { odile: 'Hugo, without looking up from her bench', hugo: 'Odile' }, mood: { odile: 'off-hand gift she would deny; then deadpan pride on "J\'y ai beaucoup travaillé"; "Merci." genuinely pleased', hugo: 'dry; the last thought quiet, let it sit' } }],
  ['ch4.day8.painted', { scene: 'Ch4: the painted door, the first thing holding colour', to: { hugo: 'himself', odile: 'Hugo' }, mood: { hugo: 'quietly amazed, deadpan', odile: 'teasing' } }],
];
