// Voice rules and voice-direction context for Ch5 « Qui a huilé le rideau ? » (src/story/ch5.js; Week 4 moved from
// ch4.week4) and its minigames' text (L.games.photo / puncture / croissant, src/story/text/games/ch5.js).
// Read by scripts/voice/extract-lines.mjs (rule syntax and kinds: see the table comment there). The chapter's
// builder owns this file: add a rule for every new text key, or extract-lines reports it as UNCLASSIFIED.

export const RULES = [
  ['ch5.title', { kind: 'none', why: 'title' }],
  ['ch5.cards.**', { kind: 'none', why: 'card' }],
  ['ch5.captions.**', { kind: 'none', why: 'caption' }],
  ['ch5.objectives.**', { kind: 'none', why: 'objective' }],
  ['ch5.prompts.**', { kind: 'none', why: 'prompt' }],
  ['ch5.needs.*', { kind: 'say', use: 'Hotspots needsLine: d.say(T.needs.<spot>)' }],
  // Week 2
  ['ch5.week2.neon', { kind: 'bark', use: 'ch5.js: d.thought(line.text, 4, {who}) within 4.5 m of the neon' }],
  ['ch5.week2.radio', { kind: 'descend' }],
  ['ch5.week2.radio.radio', { kind: 'bark', speaker: 'radio_fishing', delivery: 'radio', use: 'ch5.js: d.say([{who: "Radio", text}]) (the station)' }],
  ['ch5.week2.radio.after', { kind: 'say', use: 'd.say(T.week2.radio.after)' }],
  ['ch5.week2.end', { kind: 'think', use: 'ch5.js: d.thought(T.week2.end)' }],
  ['ch5.week2.*', { kind: 'say', use: 'd.say(T.week2.<beat>)' }],
  // Week 3
  ['ch5.week3.dawn', { kind: 'think', use: 'ch5.js: d.thought(T.week3.dawn[i]) at spawn' }],
  ['ch5.week3.segment.**', { kind: 'none', why: 'ui' }],
  ['ch5.week3.joMenu', { kind: 'choose', use: 'd.choose(T.week3.joMenu) (who: Jo; the Director plays the reply)' }],
  ['ch5.week3.hubDone', { kind: 'think', use: 'ch5.js: d.thought(T.week3.hubDone)' }],
  ['ch5.week3.wrapRadio', { kind: 'bark', speaker: 'radio_fishing', delivery: 'radio', use: 'ch5.js: d.say([{who: "Radio", text}]) (the station)' }],
  ['ch5.week3.*', { kind: 'say', use: 'd.say(T.week3.<beat>)' }],
  // Week 4
  ['ch5.week4.sami', { kind: 'say', use: 'd.say(T.week4.sami)' }],
  ['ch5.week4.bike', { kind: 'say', use: 'd.say(T.week4.bike)' }],
  ['ch5.week4.hold', { kind: 'say', use: 'd.say(T.week4.hold)' }],
  ['ch5.week4.needs', { kind: 'say', use: 'd.say(T.week4.needs)' }],
  ['ch5.week4.keyTake', { kind: 'think', use: 'ch5.js: d.thought(T.week4.keyTake)' }],
  ['ch5.week4.truing.hint', { kind: 'none', why: 'hint' }],
  ['ch5.week4.truing.gauge', { kind: 'none', why: 'ui' }],
  ['ch5.week4.truing.pitch.**', { kind: 'none', why: 'ui' }],
  ['ch5.week4.truing.flat', { kind: 'think', use: 'truing.js: d.thought(text.flat, 3)' }],
  ['ch5.week4.truing.barks', { kind: 'bark', use: 'truing.js: ui.thought(barks[key], 2.4, {who})' }],
  ['ch5.week4.truing.assisted', { kind: 'bark', use: 'truing.js: ui.thought(a.text, 2.6, {who})' }],
  ['ch5.week4.joEnter', { kind: 'bark', use: 'ch5.js: d.thought(line.text, 4, {who}) 6 s into TRUING' }],
  ['ch5.week4.after', { kind: 'say', use: 'd.say(T.week4.after.slice(0, 2)) / .slice(2)' }],
  ['ch5.week4.jo', { kind: 'say', use: 'd.say(T.week4.jo)' }],
  ['ch5.week4.laughStage', { kind: 'say', use: 'd.say (stage only)' }],
  ['ch5.week4.laugh', { kind: 'say', use: 'd.say(T.week4.laugh)' }],
  ['ch5.week4.wrap', { kind: 'say', use: 'd.say(T.week4.wrap)' }],
  ['ch5.week4.end', { kind: 'say', use: 'd.say(T.week4.end)' }],

  // ---- minigames (L.games.*; the modules' text keys, docs/SCRIPT-R4.md §6.5)
  ['games.photo.hint', { kind: 'none', why: 'hint' }],
  ['games.photo.gauge', { kind: 'none', why: 'ui' }],
  ['games.photo.focus.**', { kind: 'none', why: 'ui' }],
  ['games.photo.counter', { kind: 'none', why: 'ui' }],
  ['games.photo.assist', { kind: 'none', why: 'stage' }],
  ['games.photo.good', { kind: 'think', use: 'ch5.js / ch6.js: d.think(L.games.photo.good.<target>) after the game' }],
  ['games.photo.*', { kind: 'think', use: 'photo.js: say(ctx, line) after a missed shot (Hugo, inner)' }],
  ['games.puncture.hint.**', { kind: 'none', why: 'hint' }],
  ['games.puncture.steps.**', { kind: 'none', why: 'hint' }],
  ['games.puncture.gauge', { kind: 'none', why: 'ui' }],
  ['games.puncture.barks', { kind: 'bark', speaker: 'sami', use: 'puncture.js: say(ctx, barks[key], secs, who="Sami")' }],
  ['games.puncture.afterPatch', { kind: 'think', use: 'puncture.js: say(ctx, T.afterPatch, 3.4) (Hugo, inner)' }],
  ['games.puncture.tiers', { kind: 'descend' }],
  ['games.puncture.tiers.*', { kind: 'say', use: 'ch5.js: d.say([tiers[tier], ...T.week3.samiAfter])', flags: ['selected-at-runtime'] }],
  ['games.croissant.hint', { kind: 'none', why: 'hint' }],
  ['games.croissant.cue.**', { kind: 'none', why: 'ui' }],
  ['games.croissant.counter', { kind: 'none', why: 'ui' }],
  ['games.croissant.buzz', { kind: 'none', why: 'watch' }],
  ['games.croissant.buzzReply', { kind: 'think', use: 'croissant.js: strideBuzz reply (Hugo, inner)' }],
  ['games.croissant.grades', { kind: 'bark', speaker: 'benali', use: 'croissant.js: S.say(who, grade line, 3)' }],
  ['games.croissant.assist', { kind: 'bark', speaker: 'benali', use: 'croissant.js: tip(T.assist) (her hands take over)' }],
  ['games.croissant.tiers', { kind: 'bark', speaker: 'benali', use: 'croissant.js: S.say(who, tier line, 3.4) at the end', flags: ['selected-at-runtime'] }],
];

// Longest-prefix match on the key path; to / mood can be per speaker. English: direction for the voice model.
export const CONTEXT = [
  ['ch5', { scene: 'Ch5: weeks 2-4 after the race, Hugo in a walking boot; somebody fixes the street at night and he starts an investigation', to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'dry, practical, deadpan', hugo: 'dry, curious despite himself' } }],
  ['ch5.needs', { scene: 'Ch5: the slipper print, no chalk on him', to: 'himself', mood: 'dry' }],
  ['ch5.week2.workshop', { scene: "Ch5, week 2 (Odile's workshop, morning): the missing spoke key came back in the night, cleaned, with folded rags", to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'dry, a measured three-count indictment of Hugo, deadpan', hugo: 'dodging, almost a smile' } }],
  ['ch5.week2.neon', { scene: 'Ch5: Gérard calls from his kebab counter as Hugo passes', to: 'Hugo, across the pavement', mood: 'pre-emptive, proud, defensive about his flickering neon' }],
  ['ch5.week2.rags', { scene: 'Ch5: the folded rags left with the key', to: 'himself', mood: 'puzzled, dry' }],
  ['ch5.week2.radio', { scene: "Ch5: Odile's one-station radio, the fishing man", to: { radio_fishing: 'the listeners', odile: 'Hugo' }, mood: { radio_fishing: 'slow, certain, pompous', odile: 'deadpan' } }],
  ['ch5.week2.benali', { scene: "Ch5: Mme Benali at her bakery; her shutter screamed for 13 years and someone oiled it overnight", to: { benali: 'Hugo', hugo: 'Mme Benali / himself' }, mood: { benali: 'bewildered, chatty, searching for words', hugo: 'dry' } }],
  ['ch5.week2.photoDone', { scene: 'Ch5: after Hugo photographs the oiled shutter rail', to: { benali: 'Hugo', hugo: 'himself' }, mood: { benali: 'satisfied, then puzzled', hugo: 'dry self-mockery' } }],
  ['ch5.week2.end', { scene: 'Ch5: walking away from the bakery', to: 'himself', mood: 'wry, a little envious' }],
  ['ch5.week3.dawn', { scene: 'Ch5, week 3, Saturday 4:10 a.m.: the dark street, only the bakery lit; he used to run past it every morning', to: 'himself', mood: 'tired, wistful, dry' }],
  ['ch5.week3.benali', { scene: 'Ch5: the bakery at 4 a.m., Mme Benali in tiny slippers', to: { benali: 'Hugo', hugo: 'Mme Benali' }, mood: { benali: 'surprised, kind, serene; amused at herself', hugo: 'dry' } }],
  ['ch5.week3.benaliAfter', { scene: 'Ch5: after the croissants (they came out as moons)', to: 'Hugo', mood: 'warm, teasing' }],
  ['ch5.week3.brief', { scene: 'Ch5, 10 a.m. in the workshop: Odile sends Hugo to measure the repaired bench', to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'brisk orders, then deadpan', hugo: 'dry' } }],
  ['ch5.week3.oldmanLook', { scene: 'Ch5: an old man asleep at the end of the bench', to: 'himself', mood: 'flat, observant' }],
  ['ch5.week3.bench', { scene: 'Ch5: Hugo measures the three new slats; the old man at the end of the bench wakes', to: { hugo: 'the tape / the old man', durand: 'Hugo' }, mood: { hugo: 'muttering numbers, then polite', durand: 'old, unhurried, courteous; waking slowly; light, never sad' } }],
  ['ch5.week3.bastien', { scene: 'Ch5: Bastien jogging on the spot by the billboard, slightly out of breath', to: { bastien: 'Hugo', hugo: 'Bastien' }, mood: { bastien: 'hearty; a proud recital of his data, then suddenly sour and outraged about being second', hugo: 'dry' } }],
  ['ch5.week3.bastienAfter', { scene: 'Ch5: the STRIDE segment leader walks the street at 1.8 km/h at 3 a.m.', to: { hugo: 'himself', bastien: 'Hugo, jogging off' }, mood: { hugo: 'dry, intrigued', bastien: 'scornful laugh' } }],
  ['ch5.week3.jo', { scene: 'Ch5: inside ENCRE FINE, Jo\'s tattoo shop, a tattoo machine buzzing low', to: { jo: 'Hugo', hugo: 'Jo / himself' }, mood: { jo: 'warm, loud, quick, a laugh behind it; flirty; fond and proud about her tattoos', hugo: 'dry, a little flustered' } }],
  ['ch5.week3.joMenu', { scene: 'Ch5: Jo asked what he learned lately', to: 'Hugo', mood: 'unimpressed by kilometres, delighted by learning' }],
  ['ch5.week3.joAfter', { scene: 'Ch5: Jo sees him out', to: 'Hugo', mood: 'light, a wink in the voice' }],
  ['ch5.week3.lou', { scene: 'Ch5: Lou, 16, on the kerb, eyes on her phone', to: { lou: 'Hugo', hugo: 'Lou / himself' }, mood: { lou: 'deadpan, flat', hugo: 'dry' } }],
  ['ch5.week3.gerard', { scene: 'Ch5: Gérard at his counter window, the neon flickering', to: { gerard: 'Hugo', hugo: 'Gérard' }, mood: { gerard: 'defensive, proud, laconic', hugo: 'dry' } }],
  ['ch5.week3.print', { scene: "Ch5: a sawdust slipper print on No. 14's doorstep", to: 'himself', mood: 'dry, detective parody' }],
  ['ch5.week3.hubDone', { scene: 'Ch5: end of the Saturday morning interviews', to: 'himself', mood: 'dry, amused' }],
  ['ch5.week3.sami', { scene: 'Ch5, 4 p.m. in the workshop: Sami bursts in with a punctured tyre', to: { sami: 'Odile / Hugo', odile: 'Sami', hugo: 'Sami' }, mood: { sami: 'upset, out of breath, literal, honest', odile: 'without looking up; dry', hugo: 'dry' } }],
  ['ch5.week3.samiAfter', { scene: 'Ch5: the tube is patched', to: { sami: 'Hugo', hugo: 'Sami', odile: 'Hugo' }, mood: { sami: 'proud', hugo: 'patient', odile: 'offhand order' } }],
  ['ch5.week3.wrap', { scene: 'Ch5: Odile asks where the investigation stands; she turns the blue paint chip over and says nothing', to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'dry, neutral', hugo: 'listing, dry' } }],
  ['ch5.week3.wrapRadio', { scene: "Ch5: Odile's radio, the fishing man", to: 'the listeners', mood: 'slow, certain, pompous' }],
  ['ch5.week3.wrapEnd', { scene: 'Ch5: Odile on the radio fishing man', to: 'Hugo', mood: 'deadpan' }],
  ['ch5.week4', { scene: 'Ch5, week 4 (workshop): Sami ducks in with a bike far too big for him', to: { sami: 'Odile then Hugo', odile: 'Sami', hugo: 'Sami' }, mood: { sami: 'cheeky, out of breath, literal', odile: 'dry deflection', hugo: 'dry, patient' } }],
  ['ch5.week4.bike', { scene: 'Ch5: Hugo diagnoses the wheel', to: 'himself', mood: 'expert, focused, calm' }],
  ['ch5.week4.needs', { scene: 'Ch5: he needs the spoke key; for once it is on the pegboard', to: 'himself', mood: 'dry' }],
  ['ch5.week4.keyTake', { scene: 'Ch5: the spoke key, back and clean', to: 'himself', mood: 'quiet, puzzled' }],
  ['ch5.week4.truing', { scene: 'Ch5: Sami holds the bike while Hugo trues the wheel', to: { sami: 'Hugo / Odile', hugo: 'himself' }, mood: { sami: 'impatient kid commentary', hugo: 'focused' } }],
  ['ch5.week4.joEnter', { scene: 'Ch5: Jo walks into the workshop during the truing', to: 'Odile, across the room', mood: 'loud, breezy' }],
  ['ch5.week4.after', { scene: 'Ch5: the wheel spins true', to: { sami: 'Hugo', hugo: 'Sami' }, mood: { sami: 'delighted, nosy', hugo: 'patient, amused' } }],
  ['ch5.week4.jo', { scene: 'Ch5: Jo saw Hugo true a wheel by ear', to: { jo: 'Hugo', hugo: 'Jo / Sami', sami: 'Hugo', odile: 'Jo' }, mood: { jo: 'genuinely impressed, no irony; then unbothered, delighted', hugo: 'flustered', sami: 'genuinely asking', odile: 'without looking up; the driest line' } }],
  ['ch5.week4.laugh', { scene: 'Ch5: Hugo just laughed, rusty, for the first time in ages', to: 'himself', mood: 'surprised at himself' }],
  ['ch5.week4.wrap', { scene: 'Ch5: wheels were always his thing', to: { hugo: 'Odile', odile: 'Hugo' }, mood: { hugo: 'quiet admission', odile: 'nodding, offhand' } }],
  ['ch5.week4.end', { scene: 'Ch5: the spoke key goes back on its outline', to: 'Hugo', mood: 'dry, pointed' }],
  ['games.photo', { scene: 'Ch5 PHOTO minigame: Hugo photographs a clue with his phone', to: 'himself', mood: 'dry self-mockery' }],
  ['games.puncture', { scene: 'Ch5 PUNCTURE minigame: Hugo finds the hole in Sami\'s inner tube in a bucket of water', to: { sami: 'Hugo', hugo: 'himself' }, mood: { sami: 'excited kid commentary, fast', hugo: 'dry, remembering' } }],
  ['games.croissant', { scene: 'Ch5 CROISSANT minigame: Mme Benali teaches Hugo to roll croissants at 4 a.m.', to: { benali: 'Hugo', hugo: 'the watch' }, mood: { benali: 'warm, teasing, grading each croissant', hugo: 'dry refusal' } }],
];
