// Voice rules and voice-direction context for Ch6 « Service de nuit » (src/story/ch6.js; Week 7 moved from ch4.week7)
// and its minigames' text (src/story/text/games/ch6.js: L.games.kebab, keyRing, stencil, deduction, stakeout).
// Read by scripts/voice/extract-lines.mjs (rule syntax and kinds: see the table comment there). The chapter's
// builder owns this file: add a rule for every new text key, or extract-lines reports it as UNCLASSIFIED.
// SCRIPT-R4 §12.2 asks for a `hushed` delivery at the stakeout and the phone band for Odile's hints: there is no
// `hushed` delivery in extract-lines yet, so those lines are `spoken` with « chuchoté » in their context.

export const RULES = [
  ['ch6.title', { kind: 'none', why: 'title' }],
  ['ch6.cards.**', { kind: 'none', why: 'card' }],
  ['ch6.captions.**', { kind: 'none', why: 'caption' }],
  ['ch6.objectives.**', { kind: 'none', why: 'objective' }],
  ['ch6.prompts.**', { kind: 'none', why: 'prompt' }],
  ['ch6.needs.*', { kind: 'say', use: 'hotspot needsLine (the bike-shop door before the key ring)' }],
  // Week 5
  ['ch6.week5', { kind: 'say', use: 'd.say(T.week5) after the card' }],
  // Week 6
  ['ch6.week6.kebabIntro', { kind: 'say', use: 'd.say(I.slice(...)) at the counter' }],
  ['ch6.week6.receipts', { kind: 'say', use: 'd.say(R6.slice(...)) after KEBAB WRAP' }],
  ['ch6.week6.buzz', { kind: 'none', why: 'watch' }],
  ['ch6.week6.buzzReply', { kind: 'think', use: 'd.thought(T.week6.buzzReply, 2.6)' }],
  ['ch6.week6.lou', { kind: 'bark', use: 'd.thought(lou.text, 3.4, {who: "Lou"}) from her window, 2 h 10' }],
  ['ch6.week6.click', { kind: 'think', use: 'd.thought(click[i]) walking home, 2 h 10' }],
  ['ch6.week6.jo', { kind: 'say', use: 'd.say(B.slice(...)) at ENCRE FINE' }],
  ['ch6.week6.keyRing.mystery', { kind: 'say', use: 'd.say(M.slice(...)) at the bike-shop door' }],
  ['ch6.week6.shop.*', { kind: 'say', use: 'd.say(SH.<spot>) inside CYCLES DURAND' }],
  ['ch6.week6.shopOut', { kind: 'say', use: 'd.say(shopOut.slice(...))' }],
  ['ch6.week6.soup', { kind: 'say', use: 'd.say(soup.slice(...)) in the workshop (optional)' }],
  // Week 7 (moved, unchanged)
  ['ch6.week7.raceBike', { kind: 'say', use: 'd.say(T.week7.raceBike)' }],
  ['ch6.week7.stage', { kind: 'say', use: 'd.say (stage only)' }],
  ['ch6.week7.intro', { kind: 'say', use: 'd.say(B7.intro.slice(0,5)), pause 0.9 s, d.say(B7.intro.slice(5))' }],
  ['ch6.week7.lettering.paint', { kind: 'none', why: 'data' }],
  ['ch6.week7.lettering.tiers.*', { kind: 'say', use: 'd.say(tiers[good|middle|poor])', flags: ['selected-at-runtime'] }],
  ['ch6.week7.signMenu', { kind: 'menu', use: 'd.correct(B7.signMenu)' }],
  ['ch6.week7.signThink', { kind: 'say', use: 'd.say(B7.signThink)' }],
  ['ch6.week7.buzz', { kind: 'none', why: 'watch' }],
  ['ch6.week7.buzzReply', { kind: 'think', use: 'd.thought(B7.buzzReply, 2.4)' }],
  ['ch6.week7.wrap', { kind: 'say', use: 'd.say(B7.wrap)' }],
  // Week 7 (R4)
  ['ch6.week7.joEnter', { kind: 'say', use: 'd.say(E.slice(...)) after raceBike' }],
  ['ch6.week7.radioStation', { kind: 'bark', delivery: 'radio', speakers: { fishing: 'radio_fishing' }, use: 'd.thought(R.fishing, 5.5, {who: "Radio"}) (optional radio, Week 7)' }],
  ['ch6.week7.radio', { kind: 'say', use: 'd.say(T.week7.radio) after the station' }],
  ['ch6.week7.joBack', { kind: 'say', use: 'd.say(B.slice(...)) at 18 h' }],
  ['ch6.week7.stayMenu', { kind: 'choose', use: 'd.choose(T.week7.stayMenu) (who: Jo; option 2 who: Odile)' }],
  ['ch6.week7.stencilIntro', { kind: 'say', use: 'd.say(T.week7.stencilIntro) at the light table' }],
  ['ch6.week7.stencilAfter', { kind: 'say', use: 'd.say(A.slice(...)) after STENCIL' }],
  // Week 8
  ['ch6.week8', { kind: 'say', use: 'd.say(T.week8) after the card' }],
  // Week 9
  ['ch6.week9.boardIntro', { kind: 'say', use: 'd.say(T.week9.boardIntro) at the cork board' }],
  ['ch6.week9.boardDone', { kind: 'say', use: 'd.say(T.week9.boardDone) after DEDUCTION' }],
  ['ch6.week9.smsFrom', { kind: 'none', why: 'ui', use: 'ui.watchBuzz title' }],
  ['ch6.week9.sms', { kind: 'none', why: 'watch', use: 'ui.watchBuzz(sms): Jo\'s text, not voiced' }],
  ['ch6.week9.smsAfter', { kind: 'say', use: 'd.say(T.week9.smsAfter)' }],
  ['ch6.week9.accuse.*', { kind: 'say', use: 'DEDUCTION onAccuse: d.say([...accuse.stage, ...accuse[id]]) (a repeat: the last line)', flags: ['selected-at-runtime'] }],
  ['ch6.week9.hint', { kind: 'say', delivery: 'voicemail', use: 'DEDUCTION onHint(1): d.say(T.week9.hint) (Odile on the phone)' }],
  ['ch6.week9.hint2.phone', { kind: 'say', delivery: 'voicemail', use: 'DEDUCTION onHint(2): d.say(hint2.phone) (on the phone)' }],
  ['ch6.week9.hint2.room', { kind: 'say', use: 'DEDUCTION onHint(2): d.say(hint2.room) (in the room)' }],
  ['ch6.week9.stakeoutIntro', { kind: 'say', use: 'd.say(I.slice(...)) on the bench (hushed)' }],
  ['ch6.week9.cuteMenu', { kind: 'choose', use: 'd.choose(T.week9.cuteMenu) (who: Jo, hushed)' }],
  ['ch6.week9.stakeoutTalk', { kind: 'say', use: 'd.say(T.week9.stakeoutTalk) (hushed)' }],
  ['ch6.week9.stakeoutBuzz', { kind: 'none', why: 'watch' }],
  ['ch6.week9.stakeoutWhisper', { kind: 'say', use: 'd.say(T.week9.stakeoutWhisper) (whispered)' }],
  ['ch6.week9.stakeoutClick', { kind: 'say', use: 'd.say(T.week9.stakeoutClick)' }],
  ['ch6.week9.bravo', { kind: 'choose', use: 'STAKEOUT onArrive: d.choose(T.week9.bravo) (who: Jo; option 1 no reply)' }],
  ['ch6.week9.bravoAfter', { kind: 'say', use: 'd.say(T.week9.bravoAfter)' }],
  ['ch6.week9.reveal', { kind: 'say', use: 'd.say(Rv.slice(...)) at CYCLES DURAND' }],
  ['ch6.week9.offer', { kind: 'say', use: 'd.say(O.slice(...))' }],
  ['ch6.week9.end', { kind: 'say', use: 'd.say(E.slice(...)) on the bench, 4 a.m.' }],

  // ---------------------------------------------------------------- the Ch6 minigames (text/games/ch6.js)
  ['games.kebab.prompts.**', { kind: 'none', why: 'ui' }],
  ['games.kebab.tubs', { kind: 'none', why: 'ui' }],
  ['games.kebab.ticket', { kind: 'none', why: 'ui' }],
  ['games.kebab.stamp', { kind: 'none', why: 'ui' }],
  ['games.kebab.counter', { kind: 'none', why: 'ui' }],
  ['games.kebab.orders', { kind: 'bark', speaker: 'gerard', use: 'kebab.js: S.say(Gérard, order.call) once per order' }],
  ['games.kebab.tea', { kind: 'bark', speaker: 'gerard', use: 'kebab.js: S.say(Gérard, T.tea) (the tea beat)' }],
  ['games.kebab.teaStage', { kind: 'say', use: 'ch6.js onTea: d.say (stage only)' }],
  ['games.kebab.lines', { kind: 'bark', speaker: 'gerard', use: 'kebab.js: S.say(Gérard, pickLine(L.<key>))', flags: ['selected-at-runtime'] }],
  ['games.kebab.assist', { kind: 'bark', speaker: 'gerard', use: 'kebab.js: S.say(Gérard, T.assist) when he takes over' }],
  ['games.kebab.assistStage', { kind: 'say', use: 'ch6.js after an assisted KEBAB WRAP (stage only)' }],
  ['games.kebab.tiers', { kind: 'bark', speaker: 'gerard', use: 'kebab.js: S.say(Gérard, tiers[tier]) at the end', flags: ['selected-at-runtime'] }],
  ['games.kebab.buzz', { kind: 'none', why: 'watch' }],
  ['games.keyRing.hint', { kind: 'none', why: 'hint' }],
  ['games.keyRing.counter', { kind: 'none', why: 'ui' }],
  ['games.keyRing.wrong', { kind: 'bark', speaker: 'jo', use: 'keyring.js: Jo\'s bark on a wrong key (bag)', flags: ['selected-at-runtime'] }],
  ['games.keyRing.assist', { kind: 'say', use: 'keyring.js: d.say(T.assist) after 3 wrong keys' }],
  ['games.keyRing.foundFast', { kind: 'say', use: 'ch6.js: d.say after KEY RING (<= 3 tries, unassisted)' }],
  ['games.stencil.hint', { kind: 'none', why: 'hint' }],
  ['games.stencil.gauge', { kind: 'none', why: 'ui' }],
  ['games.stencil.band.**', { kind: 'none', why: 'ui' }],
  ['games.stencil.lines', { kind: 'bark', speaker: 'jo', use: 'stencil.js: S.say(Jo, pickLine(lines.<key>)) at most one per 4 s', flags: ['selected-at-runtime'] }],
  ['games.stencil.tiers', { kind: 'bark', speaker: 'jo', use: 'stencil.js: S.say(Jo, tiers[tier]) at the end', flags: ['selected-at-runtime'] }],
  ['games.stencil.buzz', { kind: 'none', why: 'watch' }],
  ['games.stencil.buzzJo', { kind: 'bark', speaker: 'jo', use: 'stencil.js: strideBuzz reply (Jo)' }],
  ['games.stencil.buzzReply', { kind: 'think', use: 'stencil.js: S.say(null, buzzReply) (Hugo\'s thought)' }],
  ['games.deduction.title', { kind: 'none', why: 'ui' }],
  ['games.deduction.columns', { kind: 'none', why: 'ui' }],
  ['games.deduction.hint', { kind: 'none', why: 'hint' }],
  ['games.deduction.stamp', { kind: 'none', why: 'ui' }],
  ['games.deduction.questions.**', { kind: 'none', why: 'ui' }],
  ['games.deduction.wrongClue', { kind: 'think', use: 'deduction.js: think(pickLine(T.wrongClue))', flags: ['selected-at-runtime'] }],
  ['games.deduction.rightClue', { kind: 'think', use: 'deduction.js: think(T.rightClue[q])' }],
  ['games.deduction.toCulprit', { kind: 'think', use: 'deduction.js: think(T.toCulprit[q])' }],
  ['games.deduction.buzz', { kind: 'none', why: 'watch' }],
  ['games.deduction.idle', { kind: 'think', use: 'deduction.js: think(T.idle) (30 s idle)' }],
  ['games.stakeout.hint', { kind: 'none', why: 'hint' }],
  ['games.stakeout.gauge', { kind: 'none', why: 'ui' }],
  ['games.stakeout.seen', { kind: 'none', why: 'ui' }],
  ['games.stakeout.click', { kind: 'none', why: 'ui', use: 'the « clic » caption at the bike' }],
  ['games.stakeout.barks', { kind: 'bark', speaker: 'jo', use: 'stakeout.js: say(Jo, barks.<key>) (hushed)' }],
  ['games.stakeout.lost', { kind: 'think', use: 'stakeout.js: say(ctx, T.lost) (Hugo\'s thought)' }],
];

// Longest-prefix match on the key path; to / mood can be per speaker. English: direction for the voice model.
export const CONTEXT = [
  ['ch6.needs', { scene: 'Ch6, week 6: the locked bike-shop door', to: 'himself', mood: 'dry' }],
  ['ch6.week5', { scene: 'Ch6, week 5: he has checked the street every morning before coffee; nothing new has been fixed', to: 'himself', mood: 'self-mocking' }],
  ['ch6.week6.kebabIntro', { scene: 'Ch6, week 6, 1 a.m., behind the kebab counter: someone rewired Gérard\'s flickering neon overnight', to: { gerard: 'Hugo', hugo: 'Gérard' }, mood: { gerard: 'outraged, wounded dignity about his neon; then fast, all business when the customers come in', hugo: 'deadpan' } }],
  ['ch6.week6.receipts', { scene: 'Ch6, 2 a.m., closing time: Gérard reads his receipts from the night of the shutter as his alibi', to: { gerard: 'Hugo', hugo: 'Gérard' }, mood: { gerard: 'triumphant, then genuine grief at "juste des frites", casual about the tea man; at the end protective, a little proud', hugo: 'patient; "…Je cherchais la tomate." is flat, the scene\'s laugh' } }],
  ['ch6.week6.buzzReply', { scene: 'Ch6: his watch says 2 a.m., his body needs sleep', to: 'himself', mood: 'dry' }],
  ['ch6.week6.lou', { scene: 'Ch6, 2 a.m.: Lou calls down from her lit window above the kebab shop', to: 'Hugo', mood: 'deadpan, aggrieved, a little loud for 2 a.m.' }],
  ['ch6.week6.click', { scene: 'Ch6, 2:10 a.m., walking home up the dark street: a freewheel clicks somewhere behind him', to: 'himself', mood: 'hushed, alert, then thinking it through' }],
  ['ch6.week6.jo', { scene: 'Ch6, week 6, 3 p.m., at the door of her tattoo shop: Jo (Québécoise, 34, warm, quick)', to: { jo: 'Hugo', hugo: 'Jo' }, mood: { jo: 'teasing, a laugh behind it; asks about quality, never quantity; sincere and brisk about the soup', hugo: 'tired, dry' } }],
  ['ch6.week6.keyRing', { scene: 'Ch6: Hugo tries his own mystery key on the bike-shop door first', to: { jo: 'Hugo', hugo: 'Jo / himself' }, mood: { jo: 'amused', hugo: 'deadpan' } }],
  ['ch6.week6.shop', { scene: 'Ch6: inside the closed bike shop CYCLES DURAND, dusty, one clean corner; Jo with him', to: { hugo: 'himself', jo: 'Hugo' }, mood: { hugo: 'quiet, noticing', jo: 'delighted recognition at the photo; fond; "Tabarnouche" amazed' } }],
  ['ch6.week6.shopOut', { scene: 'Ch6: leaving the bike shop', to: 'Hugo', mood: 'brisk, pushing him towards the soup' }],
  ['ch6.week6.soup', { scene: 'Ch6: Hugo brings Odile soup from Jo', to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'it costs her to say thank you; then proud', hugo: 'quoting Jo, deadpan' } }],
  ['ch6.week7', { scene: 'Ch6, week 7 (workshop): Odile\'s hand shakes at the fine brush; she nearly asks for help', to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'gruff, vulnerable underneath; "J\'ai besoin de quelqu\'un pour—" breaks off', hugo: 'gentle' } }],
  ['ch6.week7.raceBike', { scene: 'Ch6, week 7 (workshop): he has taken the old race bike down', to: 'himself', mood: 'quiet satisfaction' }],
  ['ch6.week7.lettering', { scene: 'Ch6: Odile looks at his OPEN sign', to: 'Hugo', mood: 'grudging praise' }],
  ['ch6.week7.signMenu', { scene: 'Ch6: Odile tells him how to sign his work', to: 'Hugo', mood: 'dry; the second reply is firm and pointed' }],
  ['ch6.week7.signThink', { scene: 'Ch6: his initials on the sign', to: 'himself', mood: 'moved, understated' }],
  ['ch6.week7.buzzReply', { scene: 'Ch6: the watch says he has been still for three hours', to: 'himself', mood: 'genuinely surprised' }],
  ['ch6.week7.wrap', { scene: 'Ch6: Odile plans the mural', to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'matter-of-fact plotting', hugo: 'catching on, wary' } }],
  ['ch6.week7.joEnter', { scene: 'Ch6, week 7: Jo brings Odile\'s washed brush back to the workshop', to: { jo: 'Odile, then Hugo', odile: 'Jo (vous, "Josianne")' }, mood: { jo: 'cheerful, a look at Hugo', odile: 'precise, bossy; then deadpan approval of the slammed door' } }],
  ['ch6.week7.radioStation', { scene: 'Ch6: the fishing programme on Odile\'s radio, about an old carp that never sleeps', to: 'listeners', mood: 'radio host, unhurried' }],
  ['ch6.week7.radio', { scene: 'Ch6: Odile and the radio', to: 'Hugo', mood: 'changes her mind mid-line' }],
  ['ch6.week7.joBack', { scene: 'Ch6, 6 p.m.: Jo looks at the OPEN sign and finds his tiny initials', to: { jo: 'Hugo', hugo: 'Jo' }, mood: { jo: 'soft, then inviting', hugo: 'quiet' } }],
  ['ch6.week7.stayMenu', { scene: 'Ch6: Jo asks him to come; Odile pretends not to listen', to: { jo: 'Hugo', odile: 'Hugo' }, mood: { jo: 'delighted ("Tiguidou")', odile: 'gruff, sending him off' } }],
  ['ch6.week7.stencilIntro', { scene: 'Ch6: Jo\'s light table, she teaches him to trace a stencil', to: { jo: 'Hugo', hugo: 'Jo' }, mood: { jo: 'grinning teacher', hugo: 'serious' } }],
  ['ch6.week7.stencilAfter', { scene: 'Ch6: after his first stencil', to: 'Hugo', mood: 'warm, flirtatious, never mocking' }],
  ['ch6.week8', { scene: 'Ch6, week 8: the bench holds, the neon no longer flickers', to: 'himself', mood: 'dry' }],
  ['ch6.week9.boardIntro', { scene: 'Ch6, week 9, 11 p.m., his flat: a cork board beside the 38 race bibs', to: 'himself', mood: 'dry, focused' }],
  ['ch6.week9.boardDone', { scene: 'Ch6: the three strings meet on M. Durand', to: 'himself', mood: 'certain, quiet' }],
  ['ch6.week9.smsAfter', { scene: 'Ch6: Jo texts that she is coming with soup', to: 'himself', mood: 'small smile' }],
  ['ch6.week9.accuse', { scene: 'Ch6: Scène imaginée par Hugo: he pictures accusing a neighbour at his cork board', to: { hugo: 'the suspect', sami: 'Hugo', lou: 'Hugo', gerard: 'Hugo', benali: 'Hugo', bastien: 'Hugo', jo: 'Hugo' }, mood: { hugo: 'earnest detective', sami: 'offended', lou: 'deadpan', gerard: 'proud, threatening to reread', benali: 'amused, patient', bastien: 'wounded, absolutely sincere', jo: 'flirty' } }],
  ['ch6.week9.hint', { scene: 'Ch6: Odile phones from the workshop downstairs; she can hear his boot pacing', to: 'Hugo', mood: 'dry, on the phone' }],
  ['ch6.week9.hint2', { scene: 'Ch6: Odile comes up three floors to finish his board', to: 'Hugo', mood: 'on the phone, then in the room, a little out of breath' }],
  ['ch6.week9.stakeoutIntro', { scene: 'Ch6, 2:50 a.m., on the repaired bench, chuchoté (whispered stakeout)', to: { jo: 'Hugo', hugo: 'Jo' }, mood: { jo: 'hushed, fond; "T\'es cute" reading his notebook', hugo: 'hushed' } }],
  ['ch6.week9.cuteMenu', { scene: 'Ch6: the stakeout, chuchoté', to: 'Hugo', mood: 'hushed; the second reply is moved' }],
  ['ch6.week9.stakeoutTalk', { scene: 'Ch6: the stakeout, chuchoté', to: { hugo: 'Jo', jo: 'Hugo' }, mood: { hugo: 'hushed', jo: 'hushed, sincere; the laugh on "Gérard"' } }],
  ['ch6.week9.stakeoutWhisper', { scene: 'Ch6: his watch congratulates him on a 3 a.m. outing while he sits; chuchoté', to: { jo: 'Hugo', hugo: 'Jo' }, mood: 'whisper' }],
  ['ch6.week9.stakeoutClick', { scene: 'Ch6: the click far up the street at 3:10 a.m.', to: 'himself', mood: 'hushed, alert' }],
  ['ch6.week9.bravo', { scene: 'Ch6: Jo presses Bravo on Hugo\'s phone for the old man', to: 'Hugo', mood: 'hushed, of course' }],
  ['ch6.week9.bravoAfter', { scene: 'Ch6: an old man\'s watch buzzes with a bravo at 3 a.m.', to: 'himself', mood: 'baffled, not alarmed' }],
  ['ch6.week9.reveal', { scene: 'Ch6: Albert Durand, 81, caught pinning his shop card back up at 3 a.m.; the reveal', to: { durand: 'Hugo (vous, "jeune homme"); Jo ("mademoiselle")', hugo: 'Durand', jo: 'Durand' }, mood: { durand: 'unhurried, precise, courteous, never sad on purpose; proud then a little ashamed of the stopwatch times', hugo: 'quiet; the hardest line is to himself', jo: 'warm' } }],
  ['ch6.week9.offer', { scene: 'Ch6: Hugo asks Durand to teach Sami by day', to: { hugo: 'Durand', durand: 'Hugo; Jo for "Volontiers, mademoiselle"' }, mood: { hugo: 'plain, almost smiling at the coffee joke', durand: 'reluctant, then the laugh "Ça fait cinquante ans"' } }],
  ['ch6.week9.end', { scene: 'Ch6, 4 a.m., the three of them on the bench as the bakery lights up', to: { jo: 'Hugo', hugo: 'himself' }, mood: { jo: 'fond', hugo: 'contented' } }],
  ['games.kebab', { scene: 'Ch6 KEBAB WRAP: Gérard barks orders fast at Hugo behind the counter', to: 'Hugo', mood: 'fast, laconic, outraged warmly at mistakes' }],
  ['games.keyRing', { scene: 'Ch6 KEY RING: Hugo tries fourteen keys; Jo watches', to: { jo: 'Hugo', hugo: 'Jo' }, mood: { jo: 'amused, teasing; she tied the red ribbon herself', hugo: 'realising' } }],
  ['games.stencil', { scene: 'Ch6 STENCIL: Hugo traces a swallow at Jo\'s light table', to: 'Hugo', mood: 'Jo delighted whatever happens; Hugo dry' }],
  ['games.deduction', { scene: 'Ch6 DEDUCTION: Hugo\'s cork board, 11 p.m.', to: 'himself', mood: 'focused, dry' }],
  ['games.stakeout', { scene: 'Ch6 STAKEOUT: on the bench at 3 a.m. watching the old man, chuchoté', to: { jo: 'Hugo', hugo: 'himself' }, mood: 'hushed whisper' }],
];
