// Voice rules and voice-direction context for Ch7 « Le Mur » (src/story/ch7.js, ch7jobs.js, ch7panel.js; was ch5 before Revision 4).
// Read by scripts/voice/extract-lines.mjs (rule syntax and kinds: see the table comment there). The chapter's
// builder owns this file: add a rule for every new text key, or extract-lines reports it as UNCLASSIFIED.

export const RULES = [
  ['ch7.title', { kind: 'none', why: 'title' }],
  ['ch7.cards.**', { kind: 'none', why: 'card' }],
  ['ch7.objectives.**', { kind: 'none', why: 'objective' }],
  ['ch7.prompts.**', { kind: 'none', why: 'prompt' }],
  ['ch7.signs.**', { kind: 'none', why: 'sign' }],
  ['ch7.weeks10', { kind: 'say', use: 'd.say(T.weeks10) over black, after the « Semaines 10 et 11. » card (R4)' }],
  ['ch7.opening', { kind: 'say', use: 'd.say(T.opening)' }],
  ['ch7.durand.meet', { kind: 'say', use: 'ch7.js durandMeet: d.say(M.slice(...)) in three parts, after T.opening (R4)' }],
  ['ch7.durand.panel', { kind: 'say', use: 'hotspot durandPanel: d.say(T.durand.panel) (R4, optional)' }],
  ['ch7.jo.panel', { kind: 'say', use: 'hotspot joPanel: d.say(T.jo.panel.slice(0,3)); d.say(slice(3)) (R4, optional)' }],
  ['ch7.jo.supper.ask', { kind: 'say', use: 'ch7.js joSupper: d.say(SUP.ask) (R4)' }],
  ['ch7.jo.supper.warm', { kind: 'say', use: 'joSupper: d.say(SUP.warm) when joWarmth() >= 3', flags: ['selected-at-runtime'] }],
  ['ch7.jo.supper.cool', { kind: 'say', use: 'joSupper: d.say(SUP.cool) when joWarmth() < 3 (stage only)', flags: ['selected-at-runtime'] }],
  ['ch7.jo.supper.bye', { kind: 'say', use: 'joSupper: d.say(SUP.bye)' }],
  ['ch7.benali', { kind: 'say', use: 'talk(n, T.benali) -> d.say' }],
  ['ch7.ines', { kind: 'say', use: 'talk(n, T.ines) -> d.say' }],
  ['ch7.marco', { kind: 'say', use: 'talk(n, T.marco) -> d.say' }],
  ['ch7.shopCard', { kind: 'say', use: 'd.say(T.shopCard)' }],
  ['ch7.boltHoles', { kind: 'say', use: 'd.say(T.boltHoles)' }],
  ['ch7.jobs.shutter.near', { kind: 'bark', use: 'ch7jobs: api.bark(line.text, line.who, 3) on approach' }],
  ['ch7.jobs.shutter.gauge', { kind: 'none', why: 'ui' }],
  ['ch7.jobs.shutter.mash', { kind: 'bark', use: 'ch7jobs: ui.thought(m.text, 2.4, {who})' }],
  ['ch7.jobs.shutter.done', { kind: 'say', use: 'ch7jobs: d.say(T().shutter.done)' }],
  ['ch7.jobs.shutter.call', { kind: 'bark', use: 'ch7jobs.callShutter: api.bark(c.text, c.who, 3.2) from up the street' }],
  ['ch7.jobs.radio.near', { kind: 'bark', use: 'ch7jobs: api.bark on approach' }],
  ['ch7.jobs.radio.hint', { kind: 'none', why: 'hint' }],
  ['ch7.jobs.radio.stations', {
    kind: 'bark', delivery: 'radio', use: 'crafts/radio.js: ui.thought(text.stations[id], 2.6, {who: "Radio"}) when a station is found',
    speakers: { fishing: 'radio_fishing', football: 'radio_football', forecast: 'radio_forecast' },
    notes: { fishing: 'never captioned today (found quietly at start); the clip can serve as the radio voice bed' },
  }],
  ['ch7.jobs.radio.done', { kind: 'say', use: 'ch7jobs: d.say(T().radio.done)' }],
  ['ch7.jobs.board.near', { kind: 'bark', use: 'ch7jobs: api.bark on approach' }],
  ['ch7.jobs.board.word', { kind: 'none', why: 'sign' }],
  ['ch7.jobs.board.tiers.*', { kind: 'say', use: 'ch7jobs: d.say(tiers[...])', flags: ['selected-at-runtime'] }],
  ['ch7.jobs.wheel.near', { kind: 'bark', use: 'ch7jobs: api.bark on approach' }],
  ['ch7.jobs.wheel.truing.flat', { kind: 'think', use: 'truing.js: d.thought(text.flat, 3)' }],
  ['ch7.jobs.wheel.truing.barks', { kind: 'bark', use: 'truing.js: ui.thought(barks[key], 2.4, {who})' }],
  ['ch7.jobs.wheel.truing.assisted', { kind: 'bark', use: 'truing.js: ui.thought(a.text, 2.6, {who})' }],
  ['ch7.jobs.wheel.done', { kind: 'bark', use: 'ch7jobs: api.bark(done.text, done.who, 2.6)' }],
  ['ch7.teach.call', { kind: 'bark', use: 'bark(T.teach.call[0].text, who, 2.6)' }],
  ['ch7.teach.menu', { kind: 'menu', use: 'd.correct(T.teach.menu)' }],
  ['ch7.teach.after', { kind: 'say', use: 'd.say(after.slice(0,2)); d.say(after.slice(2))' }],
  ['ch7.teach.durand', { kind: 'bark', use: 'bark(T.teach.durand.text, who, 3) after Teach if M. Durand is within 6 m (R4)' }],
  ['ch7.panel.ask', { kind: 'say', use: 'ch7panel: d.say(T.ask)' }],
  ['ch7.panel.menu', { kind: 'choose', use: 'ch7panel: d.choose(T.menu) (replies null)' }],
  ['ch7.panel.stage', { kind: 'say', use: 'ch7panel: d.say(T.stage) (stage only)' }],
  ['ch7.panel.after.*', { kind: 'say', use: 'ch7panel: d.say(T.after[motif])', flags: ['selected-at-runtime'] }],
  ['ch7.line.setup', { kind: 'say', use: 'd.say(T.line.setup)' }],
  ['ch7.line.gauge', { kind: 'none', why: 'ui' }],
  ['ch7.line.color', { kind: 'none', why: 'data' }],
  ['ch7.line.end', { kind: 'say', use: 'd.say(T.line.end)' }],
  ['ch7.line.tiers.*', { kind: 'say', use: 'd.say(T.line.tiers[tier])', flags: ['selected-at-runtime'] }],
  ['ch7.line.sign', { kind: 'say', use: 'd.say(T.line.sign.slice(0,2)); d.say(slice(2))' }],
  ['ch7.line.photo', { kind: 'say', use: 'd.say(T.line.photo)' }],
  ['ch7.club.greet', { kind: 'say', use: 'd.say(T.club.greet)' }],
  ['ch7.club.after', { kind: 'say', use: 'd.say(T.club.after)' }],
  ['ch7.club.afterThoughts', { kind: 'say', use: 'd.say(T.club.afterThoughts)' }],
  ['ch7.boot.*', { kind: 'say', use: 'd.say(T.boot.<beat>)' }],
  ['ch7.walk.sami', { kind: 'bark', use: 'bark(B0[i].text, B0[i].who) at 0 / 2.5 / 4.7 s' }],
  ['ch7.walk.firstJog', { kind: 'think', use: 'thoughtSoon(T.walk.firstJog) -> bark(text, null)' }],
  ['ch7.walk.stopped', { kind: 'think', use: 'thoughtSoon(T.walk.stopped)' }],
  ['ch7.walk.mural', { kind: 'think', use: 'thoughtSoon(T.walk.mural)' }],
  ['ch7.walk.bike', { kind: 'think', use: 'thoughtSoon(T.walk.bike)' }],
  ['ch7.walk.durand', { kind: 'bark', use: 'barkSoon(T.walk.durand) passing CYCLES DURAND (R4)' }],
  ['ch7.walk.jo.*', { kind: 'bark', use: 'barkSoon(T.walk.jo.warm | .cool) passing ENCRE FINE (R4, joWarmth())', flags: ['selected-at-runtime'] }],
  ['ch7.walk.watchHud.**', { kind: 'none', why: 'watch' }],
  ['ch7.walk.outline', { kind: 'say', use: 'd.say(T.walk.outline)' }],
  ['ch7.walk.restMenu', { kind: 'choose', use: 'd.choose(menu) then d.think(opt.reply)' }],
  ['ch7.readyCheck', { kind: 'menu', use: 'ch7.js: d.choose(T.readyCheck) (who + prompt + Ready/Not yet; prompt not voiced like every menu prompt)' }],
  ['ch7.walk.crane', { kind: 'say', use: 'd.say(T.walk.crane)' }],
];

// Longest-prefix match on the key path; to / mood can be per speaker. English: direction for the voice model.
export const CONTEXT = [
  ['ch7', { scene: 'Ch7, week 12: Rue des Tanneurs by day, neighbours painting the blind wall', to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'dry, fond underneath', hugo: 'light, at ease' } }],
  ['ch7.weeks10', { scene: 'Ch7: card "Weeks 10 and 11": old M. Durand teaches Sami to build a wheel, Sami teaches him to switch off his watch', to: 'himself', mood: 'amused, fond' }],
  ['ch7.durand', { scene: "Ch7: M. Durand, 81, the street's secret night fixer, now found, sits on a chair next to Odile's; he slept until half past eight for the first time in years", to: { durand: 'Hugo, then Odile', odile: 'Durand, then Hugo', hugo: 'Odile' }, mood: { durand: 'amazed, a little scandalised; old-fashioned, warm', odile: 'flat, practical; she knew all along and believes she needed nothing', hugo: 'surprised, half accusing, fond' } }],
  ['ch7.durand.panel', { scene: 'Ch7: M. Durand about his mural panel, a spoke key he made fifty-five years ago', to: { durand: 'Hugo', hugo: 'Durand' }, mood: { durand: 'quietly proud; the last "Elle tient." pleased', hugo: 'admiring' } }],
  ['ch7.jo', { scene: 'Ch7: Jo, the Québécoise tattoo artist from ENCRE FINE, at her tiny mural panel (a swallow)', to: { jo: 'Hugo', hugo: 'Jo' }, mood: { jo: 'confident, light; the last line caught off guard, pleased', hugo: 'sincere, simple' } }],
  ['ch7.jo.supper', { scene: 'Ch7: after the photo, Jo arrives at his elbow and tells him he owes her a supper', to: { jo: 'Hugo', hugo: 'Jo / himself' }, mood: { jo: 'certain, teasing, warm', hugo: 'flustered, honest; "En petit. Dans le coin." quietly moved' } }],
  ['ch7.teach.durand', { scene: 'Ch7: M. Durand watched Hugo talk Sami through the chain', to: 'Hugo', mood: 'approving, slow' }],
  ['ch7.walk.durand', { scene: 'Ch7 golden hour: M. Durand at the door of his reopened bike shop, Sami beside him', to: 'Hugo, across the street', mood: 'warm, dry, a touch proud of his new hours' }],
  ['ch7.walk.jo', { scene: 'Ch7 golden hour: Jo calls from the door of her tattoo shop as Hugo walks home', to: 'Hugo, across the street', mood: 'cheerful, calling out, teasing' }],
  ['ch7.opening', { scene: 'Ch7: Hugo finds Odile in her folding chair with a stick of chalk', to: { odile: 'Hugo', hugo: 'Odile / himself' }, mood: { odile: 'dry', hugo: 'light, a little surprised at himself' } }],
  ['ch7.benali', { scene: 'Ch7: Mme Benali at her mural panel', to: 'Hugo', mood: 'chatty, amused at herself' }],
  ['ch7.ines', { scene: 'Ch7: Lou at her lettering panel', to: { lou: 'Hugo', hugo: 'Lou' }, mood: { lou: 'deadpan', hugo: 'curious' } }],
  ['ch7.marco', { scene: 'Ch7: Gérard proud of his painted kebab', to: { gerard: 'Hugo', hugo: 'Gérard' }, mood: { gerard: 'proud, a little theatrical', hugo: 'polite' } }],
  ['ch7.shopCard', { scene: 'Ch7: a hand-lettered card in the bike shop window', to: 'himself', mood: 'amused, fond' }],
  ['ch7.boltHoles', { scene: 'Ch7: the bolt holes where the billboard was', to: 'himself', mood: 'wry, reflective' }],
  ['ch7.jobs.shutter', { scene: "Ch5: Mme Benali's stuck bakery shutter", to: 'Hugo', mood: 'chatty, amused' }],
  ['ch7.jobs.radio', { scene: "Ch5: Odile's radio by her chair", to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'deadpan', hugo: 'surprised' } }],
  ['ch7.jobs.radio.stations', { scene: 'Ch7: a voice coming out of an old radio as Hugo tunes it', to: 'listeners', mood: 'broadcast' }],
  ['ch7.jobs.board', { scene: "Ch5: Gérard's faded A-board, re-lettered by Hugo", to: 'Hugo', mood: 'proud, theatrical' }],
  ['ch7.jobs.wheel', { scene: "Ch5: Sami brings Lou's bent wheel", to: { sami: 'Hugo / Lou', hugo: 'himself' }, mood: { sami: 'cocky little mechanic', hugo: 'focused' } }],
  ['ch7.teach', { scene: "Ch5: Sami's chain is off; Hugo talks him through it", to: { sami: 'Hugo', hugo: 'Sami' }, mood: { sami: 'eager, then thrilled ("It went ON")', hugo: 'patient, proud' } }],
  ['ch7.panel', { scene: 'Ch7: Odile offers Hugo the billboard spot for his own panel', to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'offhand, generous without saying so', hugo: 'quietly pleased' } }],
  ['ch7.line', { scene: 'Ch7: the 20-metre line under everyone\'s panels', to: { odile: 'Hugo', hugo: 'Odile', lou: 'Hugo' }, mood: { odile: 'dry, proud underneath', hugo: 'nervous, then calm', lou: 'deadpan' } }],
  ['ch7.line.end', { scene: 'Ch7: the line is done', to: 'himself', mood: 'calm wonder' }],
  ['ch7.club', { scene: 'Ch7: the run club passes again; Bastien jogs on the spot', to: { bastien: 'Hugo', hugo: 'Bastien' }, mood: { bastien: 'loud, cheerful, breathless; "my shin\'s a bit loud" slips out', hugo: 'calm, kind, gently serious' } }],
  ['ch7.club.afterThoughts', { scene: 'Ch7: Bastien has gone', to: 'himself', mood: 'warm, no judgement' }],
  ['ch7.boot', { scene: 'Ch7: the boot comes off on the bench', to: { odile: 'Hugo', hugo: 'Odile' }, mood: { odile: 'gruff tenderness', hugo: 'light, relieved' } }],
  ['ch7.boot.light', { scene: 'Ch7: the leg out of the boot', to: 'himself', mood: 'wondering, light' }],
  ['ch7.walk', { scene: 'Ch7 finale: golden-hour walk home down the painted street', to: 'himself', mood: 'peaceful, light' }],
  ['ch7.walk.sami', { scene: 'Ch7: Sami rides past on the trued bike', to: { sami: 'Hugo, shouting while riding', hugo: 'Sami, calling after him' }, mood: { sami: 'gleeful, then grudging "fine!"', hugo: 'warning, half laughing' } }],
  ['ch7.walk.outline', { scene: 'Ch7: hanging the watch inside the outline Odile already painted', to: 'himself', mood: 'moved, quiet' }],
  ['ch7.walk.restMenu', { scene: 'Ch7: the watch asks him to move; he chooses rest', to: 'himself', mood: 'calm, settled' }],
  ['ch7.walk.crane', { scene: 'Ch7: final crane shot over the street', to: 'himself', mood: 'serene, the last words of the game' }],
];
