#!/usr/bin/env bash
# PBR materials and HDRIs (Poly Haven, CC0) plus grime overlays (ambientCG decals, CC0, and masks
# generated by materials-grime.mjs). Run by scripts/fetch-assets.sh with ROOT, CACHE and OUT set;
# it also runs on its own: `bash scripts/assets/materials.sh`. Idempotent: downloads are cached in
# $CACHE/materials and skipped when present. See docs/assets/materials.md for the catalogue.
#
# Output (all under $OUT):
#   materials/<id>/color.jpg   albedo, sRGB
#   materials/<id>/normal.jpg  tangent-space normal, OpenGL convention (+Y up), linear
#   materials/<id>/arm.jpg     R = ambient occlusion, G = roughness, B = metalness (glTF ORM), linear
#   materials/grime/*          greyscale overlay masks (linear)
#   materials/materials.json   { id: {source, tile:[w,h] metres, maps, res} } for texture repeat by world size
#   hdri/<id>.hdr              1k equirect Radiance HDR ($CACHE/materials/hdri/hdri.json lists sources)
set -euo pipefail

ROOT="${ROOT:-$(cd "$(dirname "$0")/../.." && pwd)}"
CACHE="${CACHE:-$ROOT/.cache/dl}"
OUT="${OUT:-$ROOT/public/assets}"
DL="$CACHE/materials"
PH="https://dl.polyhaven.org/file/ph-assets"
mkdir -p "$DL" "$OUT/materials" "$OUT/hdri"

fetch() { # fetch <url> <cache-file>: download once (atomically, so an interrupted run never leaves a stub)
  [[ -s "$2" ]] && return 0
  mkdir -p "$(dirname "$2")"
  echo "  downloading $(basename "$2")"
  curl -fsSL --retry 3 --retry-delay 2 -A "hairline-fetch-assets" -o "$2.part" "$1"
  mv "$2.part" "$2"
}

# ------------------------------------------------------------------------------------------ materials
# our_id | Poly Haven id | colour res (1k, or 2k for the hero surfaces) | tile metres (from Poly Haven
# 'dimensions') | chapters. Normal and ARM are always 1k: at game-camera distance the albedo carries
# the detail, and 1k normals keep each hero under 5 MB.
MATERIALS=(
  "flat_floorboards          old_wood_floor               1k 3.0  ch1"
  "plaster_painted           painted_plaster_wall         1k 2.0  ch1,ch4"
  "tile_white_long           long_white_tiles             1k 1.27 ch1"
  "fabric_wool               poly_wool_herringbone        1k 0.27 ch1"
  "street_asphalt_wet        asphalt_02                   2k 3.0  ch2,ch3,ch5"
  "street_cobbles            cobblestone_embedded_asphalt 1k 1.9  ch2,ch5"
  "street_pavement           concrete_pavement            1k 1.8  ch2,ch3,ch5"
  "concrete_grimy            concrete_wall_006            1k 2.0  ch2,ch3,ch5"
  "facade_brick_dark         red_bricks_04                2k 2.5  ch2,ch3,ch5"
  "facade_brick_painted      painted_worn_brick           1k 1.8  ch2,ch5"
  "facade_brick_plaster      red_brick_plaster_patch_02   1k 1.5  ch2,ch5"
  "facade_render             concrete_wall_008            1k 2.71 ch2,ch3,ch5"
  "shutter_rusty             rusty_metal_shutter          1k 1.9  ch2,ch4,ch5"
  "metal_painted_green       green_metal_rust             1k 1.0  ch2,ch5"
  "metal_painted_rusty       rusty_metal_02               1k 1.0  ch1,ch2,ch4,ch5"
  "metal_corrugated_rusty    rusty_corrugated_iron        1k 2.0  ch2,ch4,ch5"
  "wall_mural_render         plastered_wall_03            2k 4.0  ch2,ch5"
  "workshop_floor_concrete   garage_floor                 1k 1.89 ch4,ch5"
  "brick_whitewashed         whitewashed_brick            1k 2.0  ch4"
  "wood_planks_weathered     weathered_brown_planks       1k 1.8  ch4,ch5"
  "wood_planks_painted       distressed_painted_planks    1k 1.6  ch4"
  "wood_plywood              plywood                      1k 0.5  ch4,ch5"
  "metal_plate_worn          metal_plate_02               1k 2.0  ch4,ch5"
)

echo "PBR materials (Poly Haven, CC0)"
json="{"
for row in "${MATERIALS[@]}"; do
  read -r id src res tile chapters <<<"$row"
  dest="$OUT/materials/$id"
  mkdir -p "$dest"
  for map in diff:color:$res nor_gl:normal:1k arm:arm:1k; do
    IFS=: read -r ph ours r <<<"$map"
    file="$DL/ph/${src}_${ph}_${r}.jpg"
    fetch "$PH/Textures/jpg/$r/$src/${src}_${ph}_${r}.jpg" "$file"
    cp "$file" "$dest/$ours.jpg"
  done
  json+=$'\n'"  \"$id\": {\"source\": \"polyhaven:$src\", \"tile\": [$tile, $tile], \"maps\": [\"color\", \"normal\", \"arm\"], \"res\": {\"color\": \"$res\", \"normal\": \"1k\", \"arm\": \"1k\"}, \"chapters\": \"$chapters\"},"
done
printf '%s\n}\n' "${json%,}" >"$OUT/materials/materials.json"
# Drop material folders that are no longer in the table (never ship what isn't used).
keep=" grime "
for row in "${MATERIALS[@]}"; do read -r id _ <<<"$row"; keep+="$id "; done
for d in "$OUT/materials"/*/; do
  name="$(basename "$d")"
  [[ "$keep" == *" $name "* ]] || { echo "  removing unused materials/$name"; rm -rf "$d"; }
done

# ------------------------------------------------------------------------------------------ grime
# ambientCG decals: only the greyscale opacity mask is shipped (code tints it). Leaking003 is
# 1024x512 streaks running down from the top edge; Leaking008 is a 1024x256 band of wet dirt at the
# foot of a wall; SurfaceImperfections003 is a tileable 1024 field of vertical streaky dirt.
echo "Grime overlays (ambientCG CC0 + generated)"
mkdir -p "$OUT/materials/grime"
GRIME=(
  "leaks       Leaking003"
  "edge_dirt   Leaking008"
  "streaks     SurfaceImperfections003"
)
for row in "${GRIME[@]}"; do
  read -r id src <<<"$row"
  zip="$DL/acg/${src}_1K-JPG.zip"
  fetch "https://ambientcg.com/get?file=${src}_1K-JPG.zip" "$zip"
  unzip -o -j -q "$zip" "${src}_1K-JPG_Opacity.jpg" -d "$DL/acg/x"
  cp "$DL/acg/x/${src}_1K-JPG_Opacity.jpg" "$OUT/materials/grime/$id.jpg"
done
# Procedural masks (standing-water puddles, macro breakup): deterministic, so a regen is only needed
# when one is missing. The generator can also make oil_stains / peeling, which nothing uses yet.
need=0
for f in puddles macro; do [[ -s "$OUT/materials/grime/$f.png" ]] || need=1; done
if [[ $need == 1 ]]; then node "$ROOT/scripts/assets/materials-grime.mjs" "$OUT/materials/grime" puddles macro; fi
rm -f "$OUT/materials/grime/oil_stains.png" "$OUT/materials/grime/peeling.png"

# ------------------------------------------------------------------------------------------ HDRIs
# our_id | Poly Haven id. 1k only: these light and reflect, they are never the visible background.
HDRIS=(
  "night_street        cobblestone_street_night"
  "dawn_fog            beach_parking"
  "interior_dim        lebombo"
  "workshop            small_workshop"
  "golden_street       vatican_road"
)
echo "HDRIs (Poly Haven, CC0)"
json="{"
keep=" "
for row in "${HDRIS[@]}"; do
  read -r id src <<<"$row"
  fetch "$PH/HDRIs/hdr/1k/${src}_1k.hdr" "$DL/hdri/${src}_1k.hdr"
  cp "$DL/hdri/${src}_1k.hdr" "$OUT/hdri/$id.hdr"
  json+=$'\n'"  \"$id\": {\"source\": \"polyhaven:$src\", \"res\": \"1k\"},"
  keep+="$id.hdr "
done
printf '%s\n}\n' "${json%,}" >"$DL/hdri/hdri.json" # the source list stays in the cache: nothing loads it
rm -f "$OUT/hdri/hdri.json"
for f in "$OUT/hdri"/*.hdr; do [[ "$keep" == *" $(basename "$f") "* ]] || { echo "  removing unused hdri/$(basename "$f")"; rm -f "$f"; }; done

echo "  materials: $(du -sh "$OUT/materials" | cut -f1), hdri: $(du -sh "$OUT/hdri" | cut -f1)"
